import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          SettingC(),
        ]),
      ),
    );
  }
}

class SettingC extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 360,
          height: 800,
          clipBehavior: Clip.antiAlias,
          decoration: ShapeDecoration(
            color: Color(0xFFFAFAFB),
            shape: RoundedRectangleBorder(side: BorderSide(width: 2)),
          ),
          child: Stack(
            children: [
              Positioned(
                left: 30,
                top: 120,
                child: Container(
                  width: 300,
                  height: 122,
                  decoration: ShapeDecoration(
                    color: Color(0xFFE7E7E7),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(20),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 39,
                top: 192,
                child: Container(
                  width: 272,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 5,
                        child: Container(
                          width: 30,
                          height: 30,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/30x30"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 52,
                        top: 0,
                        child: SizedBox(
                          width: 179,
                          height: 38,
                          child: Text(
                            'Language',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 16,
                              fontFamily: 'Nunito',
                              fontWeight: FontWeight.w700,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 254,
                        top: 28,
                        child: Container(
                          width: 18,
                          height: 18,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/18x18"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 40,
                top: 132,
                child: Container(
                  width: 271,
                  height: 38,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 50,
                        top: 0,
                        child: SizedBox(
                          width: 179,
                          height: 38,
                          child: Text(
                            'Notification',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 16,
                              fontFamily: 'Nunito',
                              fontWeight: FontWeight.w700,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 4,
                        child: Container(
                          width: 30,
                          height: 30,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/30x30"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 253,
                        top: 28,
                        child: Container(
                          width: 18,
                          height: 18,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/18x18"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 81,
                top: 181,
                child: Container(
                  width: 230,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        strokeAlign: BorderSide.strokeAlignCenter,
                        color: Color(0xFFB8B8B8),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 27,
                top: 32,
                child: Container(
                  width: 23,
                  height: 23,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/23x23"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 69,
                top: 21,
                child: SizedBox(
                  width: 222,
                  height: 89,
                  child: Text(
                    'Setting',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 32,
                      fontFamily: 'Heebo',
                      fontWeight: FontWeight.w700,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 30,
                top: 94,
                child: SizedBox(
                  width: 238,
                  height: 38,
                  child: Text(
                    'General',
                    style: TextStyle(
                      color: Color(0xFFB8B8B8),
                      fontSize: 15,
                      fontFamily: 'Nunito',
                      fontWeight: FontWeight.w700,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 31,
                top: 290,
                child: Container(
                  width: 300,
                  height: 122,
                  decoration: ShapeDecoration(
                    color: Color(0xFFE7E7E7),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(20),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 44,
                top: 362,
                child: SizedBox(
                  width: 267,
                  height: 38,
                  child: Text(
                    'Fahrenheit (°F)',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 16,
                      fontFamily: 'Nunito',
                      fontWeight: FontWeight.w700,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 44,
                top: 302,
                child: SizedBox(
                  width: 267,
                  height: 38,
                  child: Text(
                    'Celsius (°C)',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 16,
                      fontFamily: 'Nunito',
                      fontWeight: FontWeight.w700,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 47,
                top: 351,
                child: Container(
                  width: 268,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        strokeAlign: BorderSide.strokeAlignCenter,
                        color: Color(0xFFB8B8B8),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 31,
                top: 264,
                child: SizedBox(
                  width: 238,
                  height: 38,
                  child: Text(
                    'Temperature unit',
                    style: TextStyle(
                      color: Color(0xFFB8B8B8),
                      fontSize: 15,
                      fontFamily: 'Nunito',
                      fontWeight: FontWeight.w700,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 287,
                top: 309,
                child: Container(
                  width: 25,
                  height: 25,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/25x25"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
        Container(
          width: 360,
          height: 800,
          clipBehavior: Clip.antiAlias,
          decoration: ShapeDecoration(
            color: Color(0xFFFAFAFB),
            shape: RoundedRectangleBorder(side: BorderSide(width: 2)),
          ),
          child: Stack(
            children: [
              Positioned(
                left: 30,
                top: 120,
                child: Container(
                  width: 300,
                  height: 122,
                  decoration: ShapeDecoration(
                    color: Color(0xFFE7E7E7),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(20),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 39,
                top: 192,
                child: Container(
                  width: 272,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 5,
                        child: Container(
                          width: 30,
                          height: 30,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/30x30"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 52,
                        top: 0,
                        child: SizedBox(
                          width: 179,
                          height: 38,
                          child: Text(
                            'Language',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 16,
                              fontFamily: 'Nunito',
                              fontWeight: FontWeight.w700,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 254,
                        top: 28,
                        child: Container(
                          width: 18,
                          height: 18,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/18x18"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 40,
                top: 132,
                child: Container(
                  width: 271,
                  height: 38,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 50,
                        top: 0,
                        child: SizedBox(
                          width: 179,
                          height: 38,
                          child: Text(
                            'Notification',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 16,
                              fontFamily: 'Nunito',
                              fontWeight: FontWeight.w700,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 4,
                        child: Container(
                          width: 30,
                          height: 30,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/30x30"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 253,
                        top: 28,
                        child: Container(
                          width: 18,
                          height: 18,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/18x18"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 81,
                top: 181,
                child: Container(
                  width: 230,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        strokeAlign: BorderSide.strokeAlignCenter,
                        color: Color(0xFFB8B8B8),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 27,
                top: 32,
                child: Container(
                  width: 23,
                  height: 23,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/23x23"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 69,
                top: 21,
                child: SizedBox(
                  width: 222,
                  height: 89,
                  child: Text(
                    'Setting',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 32,
                      fontFamily: 'Heebo',
                      fontWeight: FontWeight.w700,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 30,
                top: 94,
                child: SizedBox(
                  width: 238,
                  height: 38,
                  child: Text(
                    'General',
                    style: TextStyle(
                      color: Color(0xFFB8B8B8),
                      fontSize: 15,
                      fontFamily: 'Nunito',
                      fontWeight: FontWeight.w700,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 31,
                top: 290,
                child: Container(
                  width: 300,
                  height: 122,
                  decoration: ShapeDecoration(
                    color: Color(0xFFE7E7E7),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(20),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 44,
                top: 362,
                child: SizedBox(
                  width: 267,
                  height: 38,
                  child: Text(
                    'Fahrenheit (°F)',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 16,
                      fontFamily: 'Nunito',
                      fontWeight: FontWeight.w700,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 44,
                top: 302,
                child: SizedBox(
                  width: 267,
                  height: 38,
                  child: Text(
                    'Celsius (°C)',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 16,
                      fontFamily: 'Nunito',
                      fontWeight: FontWeight.w700,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 47,
                top: 351,
                child: Container(
                  width: 268,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        strokeAlign: BorderSide.strokeAlignCenter,
                        color: Color(0xFFB8B8B8),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 31,
                top: 264,
                child: SizedBox(
                  width: 238,
                  height: 38,
                  child: Text(
                    'Temperature unit',
                    style: TextStyle(
                      color: Color(0xFFB8B8B8),
                      fontSize: 15,
                      fontFamily: 'Nunito',
                      fontWeight: FontWeight.w700,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 287,
                top: 368,
                child: Container(
                  width: 25,
                  height: 25,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/25x25"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
        Container(
          width: 360,
          height: 800,
          clipBehavior: Clip.antiAlias,
          decoration: ShapeDecoration(
            color: Color(0xFFFAFAFB),
            shape: RoundedRectangleBorder(side: BorderSide(width: 2)),
          ),
          child: Stack(
            children: [
              Positioned(
                left: 27,
                top: 32,
                child: Container(
                  width: 23,
                  height: 23,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/23x23"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 69,
                top: 30,
                child: SizedBox(
                  width: 222,
                  height: 89,
                  child: Text(
                    'Language',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 24,
                      fontFamily: 'Heebo',
                      fontWeight: FontWeight.w700,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 30,
                top: 116,
                child: Container(
                  width: 300,
                  height: 122,
                  decoration: ShapeDecoration(
                    color: Color(0xFFE7E7E7),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(20),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 43,
                top: 188,
                child: SizedBox(
                  width: 271,
                  height: 38,
                  child: Text(
                    'Thai',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 16,
                      fontFamily: 'Nunito',
                      fontWeight: FontWeight.w700,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 43,
                top: 128,
                child: SizedBox(
                  width: 271,
                  height: 38,
                  child: Text(
                    'English',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 16,
                      fontFamily: 'Nunito',
                      fontWeight: FontWeight.w700,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 46,
                top: 177,
                child: Container(
                  width: 268,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        strokeAlign: BorderSide.strokeAlignCenter,
                        color: Color(0xFFB8B8B8),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 30,
                top: 90,
                child: SizedBox(
                  width: 238,
                  height: 38,
                  child: Text(
                    'Preferred Language',
                    style: TextStyle(
                      color: Color(0xFFB8B8B8),
                      fontSize: 15,
                      fontFamily: 'Nunito',
                      fontWeight: FontWeight.w700,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 289,
                top: 135,
                child: Container(
                  width: 25,
                  height: 25,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/25x25"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
        Container(
          width: 360,
          height: 800,
          clipBehavior: Clip.antiAlias,
          decoration: ShapeDecoration(
            color: Color(0xFFFAFAFB),
            shape: RoundedRectangleBorder(side: BorderSide(width: 2)),
          ),
          child: Stack(
            children: [
              Positioned(
                left: 27,
                top: 32,
                child: Container(
                  width: 23,
                  height: 23,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/23x23"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 69,
                top: 30,
                child: SizedBox(
                  width: 222,
                  height: 89,
                  child: Text(
                    'Language',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 24,
                      fontFamily: 'Heebo',
                      fontWeight: FontWeight.w700,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 30,
                top: 116,
                child: Container(
                  width: 300,
                  height: 122,
                  decoration: ShapeDecoration(
                    color: Color(0xFFE7E7E7),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(20),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 43,
                top: 188,
                child: SizedBox(
                  width: 271,
                  height: 38,
                  child: Text(
                    'Thai',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 16,
                      fontFamily: 'Nunito',
                      fontWeight: FontWeight.w700,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 43,
                top: 128,
                child: SizedBox(
                  width: 271,
                  height: 38,
                  child: Text(
                    'English',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 16,
                      fontFamily: 'Nunito',
                      fontWeight: FontWeight.w700,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 46,
                top: 177,
                child: Container(
                  width: 268,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        strokeAlign: BorderSide.strokeAlignCenter,
                        color: Color(0xFFB8B8B8),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 30,
                top: 90,
                child: SizedBox(
                  width: 238,
                  height: 38,
                  child: Text(
                    'Preferred Language',
                    style: TextStyle(
                      color: Color(0xFFB8B8B8),
                      fontSize: 15,
                      fontFamily: 'Nunito',
                      fontWeight: FontWeight.w700,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 289,
                top: 194,
                child: Container(
                  width: 25,
                  height: 25,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/25x25"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}